# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# COMMAND to use in our jobs.
commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  # JOB to use the commands to print circle workflow
  my_job: 
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "my_workflow"
  my_workflow:
    # Run the my_job job in its own container
    jobs:
      - my_job
